#ifndef A_FINGER_1_0_INTERAL_FLASH_H
#define A_FINGER_1_0_INTERAL_FLASH_H

#include "app_base.h"
#include "hc32_ll.h"
#include "hc32_ll_efm.h"

#include <stdint.h>

#define APP_FLASH_BASE             (APP_CODE_BASE)
#define APP_FLASH_SIZE             (APP_CODE_SIZE)
#define APP_FLASH_END              (APP_FLASH_BASE + APP_FLASH_SIZE)
#define FLASH_PAGE_SIZE            (EFM_SECTOR_SIZE)
#define FLASH_WAITETIME            50000UL
#define FLASH_WRITE_BLOCK_SIZE     8U
#define FLASH_OPERATION_RETRIES    3U
#define FLASH_PACK_WRITE_MAX_SIZE  2048U

typedef enum
{
    FLASH_UNINITIALIZED = 0,
    FLASH_READY,
    FLASH_BUSY
} flash_state_t;

typedef enum
{
    FLASH_OK = 0,
    FLASH_ERROR_ADDR,
    FLASH_ERROR_ERASE,
    FLASH_ERROR_WRITE,
    FLASH_ERROR_READ,
    FLASH_ERROR_SIZE,
    FLASH_ERROR_LOCK,
    FLASH_ERROR_UNLOCK,
    FLASH_ERROR_VERIFY,
    FLASH_ERROR_NOT_ERASED,
    FLASH_ERROR_BUSY
} flash_status_t;

flash_status_t flash_init(void);
flash_status_t flash_deinit(void);
flash_status_t flash_read_word(uint32_t addr, uint32_t *data);
flash_status_t flash_read(uint32_t addr, void *data, uint16_t length);
flash_status_t flash_write(uint32_t addr, const uint64_t *data, uint16_t length);
flash_status_t flash_erase_sector(uint32_t addr);
flash_status_t flash_verify(uint32_t addr, const uint64_t *data, uint16_t length);
flash_status_t flash_write_with_verify(uint32_t addr, const uint64_t *data, uint16_t length);
flash_status_t flash_pack_and_write(uint32_t addr, const uint8_t *data, uint32_t size);
uint8_t stmflash_get_flash_sector(uint32_t addr);
flash_state_t flash_get_state(void);

#define ADDR_FLASH_SECTOR_0        (APP_FLASH_BASE + (0UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_1        (APP_FLASH_BASE + (1UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_2        (APP_FLASH_BASE + (2UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_3        (APP_FLASH_BASE + (3UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_4        (APP_FLASH_BASE + (4UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_5        (APP_FLASH_BASE + (5UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_6        (APP_FLASH_BASE + (6UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_7        (APP_FLASH_BASE + (7UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_8        (APP_FLASH_BASE + (8UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_9        (APP_FLASH_BASE + (9UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_10       (APP_FLASH_BASE + (10UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_11       (APP_FLASH_BASE + (11UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_12       (APP_FLASH_BASE + (12UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_13       (APP_FLASH_BASE + (13UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_14       (APP_FLASH_BASE + (14UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_15       (APP_FLASH_BASE + (15UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_16       (APP_FLASH_BASE + (16UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_17       (APP_FLASH_BASE + (17UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_18       (APP_FLASH_BASE + (18UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_19       (APP_FLASH_BASE + (19UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_20       (APP_FLASH_BASE + (20UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_21       (APP_FLASH_BASE + (21UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_22       (APP_FLASH_BASE + (22UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_23       (APP_FLASH_BASE + (23UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_24       (APP_FLASH_BASE + (24UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_25       (APP_FLASH_BASE + (25UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_26       (APP_FLASH_BASE + (26UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_27       (APP_FLASH_BASE + (27UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_28       (APP_FLASH_BASE + (28UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_29       (APP_FLASH_BASE + (29UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_30       (APP_FLASH_BASE + (30UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_31       (APP_FLASH_BASE + (31UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_32       (APP_FLASH_BASE + (32UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_33       (APP_FLASH_BASE + (33UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_34       (APP_FLASH_BASE + (34UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_35       (APP_FLASH_BASE + (35UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_36       (APP_FLASH_BASE + (36UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_37       (APP_FLASH_BASE + (37UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_38       (APP_FLASH_BASE + (38UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_39       (APP_FLASH_BASE + (39UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_40       (APP_FLASH_BASE + (40UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_41       (APP_FLASH_BASE + (41UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_42       (APP_FLASH_BASE + (42UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_43       (APP_FLASH_BASE + (43UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_44       (APP_FLASH_BASE + (44UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_45       (APP_FLASH_BASE + (45UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_46       (APP_FLASH_BASE + (46UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_47       (APP_FLASH_BASE + (47UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_48       (APP_FLASH_BASE + (48UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_49       (APP_FLASH_BASE + (49UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_50       (APP_FLASH_BASE + (50UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_51       (APP_FLASH_BASE + (51UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_52       (APP_FLASH_BASE + (52UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_53       (APP_FLASH_BASE + (53UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_54       (APP_FLASH_BASE + (54UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_55       (APP_FLASH_BASE + (55UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_56       (APP_FLASH_BASE + (56UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_57       (APP_FLASH_BASE + (57UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_58       (APP_FLASH_BASE + (58UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_59       (APP_FLASH_BASE + (59UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_60       (APP_FLASH_BASE + (60UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_61       (APP_FLASH_BASE + (61UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_62       (APP_FLASH_BASE + (62UL * FLASH_PAGE_SIZE))
#define ADDR_FLASH_SECTOR_63       (APP_FLASH_BASE + (63UL * FLASH_PAGE_SIZE))

#define ADDR_FLASH_PHYSICAL_SECTOR(n)        (EFM_START_ADDR + ((uint32_t)(n) * FLASH_PAGE_SIZE))

#define ADDR_FLASH_SECTOR_FORCE_LUT_PART1    ADDR_FLASH_PHYSICAL_SECTOR(50U)
#define ADDR_FLASH_SECTOR_FORCE_LUT_PART2    ADDR_FLASH_PHYSICAL_SECTOR(51U)
#define ADDR_FLASH_SECTOR_FORCE_LUT_PART3    ADDR_FLASH_PHYSICAL_SECTOR(52U)
#define ADDR_FLASH_SECTOR_FORCE_LUT_PART4    ADDR_FLASH_PHYSICAL_SECTOR(53U)
#define ADDR_FLASH_SECTOR_FORCE_LUT_PART5    ADDR_FLASH_PHYSICAL_SECTOR(54U)
#define ADDR_FLASH_SECTOR_FORCE_LUT_PART6    ADDR_FLASH_PHYSICAL_SECTOR(55U)
#define ADDR_FLASH_SECTOR_CONFIG             ADDR_FLASH_PHYSICAL_SECTOR(58U)
#define ADDR_FLASH_SECTOR_PRESS_LUT_DATA     ADDR_FLASH_PHYSICAL_SECTOR(59U)
#define ADDR_FLASH_SECTOR_PRESS_LUT_COUNT    ADDR_FLASH_PHYSICAL_SECTOR(60U)
#define ADDR_FLASH_SECTOR_SIMPLE_PARAM       ADDR_FLASH_PHYSICAL_SECTOR(61U)
#define ADDR_FLASH_SECTOR_PRESS_MODE_FLAG    ADDR_FLASH_PHYSICAL_SECTOR(62U)
#define ADDR_FLASH_SECTOR_UPGRADE_RESERVED   ADDR_FLASH_PHYSICAL_SECTOR(63U)

#endif
